name: Setup Some stuff
description: Sets up a specific version of Node.js
inputs:
  node-version:
    description: 'Version of Node.js to use'
    required: true
    default: '14'

runs:
  using: composite
  steps:
    - run: npm --version
