on:
  workflow_call:
    inputs:
      revision:
        type: string
        required: true


jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint Step
        uses: ./.github/actions/lint-node-project
      - name: Build Step
        run: | 
          echo "Hallo Build of revision=$REVISION 🥳"
        env:
          REVISION: ${{ inputs.revision }}
