on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      stage:
        required: false
        type: string
        default: dev
    outputs:
       success:
        value: "true"

jobs:
  deploy-built-artifact:
    environment: ${{ inputs.stage }}
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: ${{ inputs.image_uri }}

    steps:
      - name: Download Artifacts
        run: | 
          echo "Downloading image IMAGE=$IMAGE_URI"
      - name: Deploy files to destination
        run: | 
          echo "Hallo Deploy IMAGE=$IMAGE_URI on stage=$STAGE against s3=$S3_PATH"
        env:
          STAGE: ${{ inputs.stage }}
          S3_PATH: ${{ vars.S3_WEBSPACE_URL }}